Array Attributes 

In [2]:
# create a Array
import numpy as np
arr=np.array([1,2,3,4,5,6]);
print(arr)

[1 2 3 4 5 6]


In [18]:
# Insert the correct argument for creating a NumPy array with 2 dimensions.
# ndim is used to find the dimention of the array
# arr=np.array([[1,2,3,4],[1,2,3,4]])
# arr=np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]]]) # - >3d
import numpy as np
arr=np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]]])
print(arr.ndim)

3


In [8]:
# arr=np.array([1,2,3,4,5])
arr=np.array([[1,2,3],[1,2,3]])
print(arr.shape)

(2, 3)


In [17]:
import numpy as np
arr = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[10, 11, 12], [13, 14, 15]],
    [[19, 20, 21], [22, 23, 24]],
    [[28,29,30],[16, 17, 18]],
    [[28,29,30],[16, 17, 18]]])
print(arr.shape)

(5, 2, 3)


In [44]:
arr=np.array([1,2,3,4])
arr1=arr.reshape(2,2)
print(arr1)
print(" no of shape is :", arr1.shape),
print(" no if size is : ", arr1.size),
print(" no of dimention is :",arr1.ndim)
arr2=np.array([1,2,3,4],ndmin=2)
print(arr2)
print(" no of dimention is :",arr2.ndim)


# Building back to one dimension using reshape


x = arr2.reshape(-1)
print(" no of shape is :", x.shape),
print(" no if size is : ", x.size),
print(" no of dimention is :",x.ndim)

[[1 2]
 [3 4]]
 no of shape is : (2, 2)
 no if size is :  4
 no of dimention is : 2
[[1 2 3 4]]
 no of dimention is : 2
 no of shape is : (4,)
 no if size is :  4
 no of dimention is : 1


In [19]:
arr = np.array([1,2,3,4,5])
print(arr[0])


1
