In [6]:
# Adding elements in array
import numpy as np

arr = np.array([1, 2, 3])
print(arr)
arr = np.append(arr, 4)  # Append a single element
print(arr)
arr = np.append(arr, [5, 6])  # Append multiple elements
print(arr)

# element will get appended at last element

[1 2 3]
[1 2 3 4]
[1 2 3 4 5 6]


In [7]:
# Inseting elements in btw array
import numpy as np

arr = np.array([1, 2, 3])
print(arr)
arr = np.insert(arr, 1, 10)  # Insert a single element at index 1
print(arr) 
arr = np.insert(arr, 2, [20, 30])  # Insert multiple elements starting from index 2
print(arr)

[1 2 3]
[ 1 10  2  3]
[ 1 10 20 30  2  3]


In [ ]:
# Removing elements

import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)
arr = np.delete(arr, 2)  # Remove element at index 2
print(arr)

In [ ]:
# Filtering the array
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
arr = arr[arr != 3]  # Remove element with value 3
print(arr)

In [ ]:
# NumPy arrays have fixed sizes once created, so these operations return new arrays with the modified content rather than modifying the original array in-place. 