In [ ]:
# Numpy it is the python library which is used for calculating matamatical operation 
# Num py means Numerical in python shortly known as Numpy
# Array defined as collection of items that are stored at contiguous memory locations.
# it is a container which can hold a fixed number of items, and these should of same type
# Combination of arrays saves a time as it reduce the overall size of the code.

In [2]:
import numpy as np

l1=[20,30,40]
l2=[50,60,90]
print(l1+l2)
# here using list values are comma (,) sepereated and it has concadinated the list


[20, 30, 40, 50, 60, 90]


In [5]:
sum1=np.array([20,30,40])
sum2=np.array([10,20,30])
print(sum1,sum2)
print(sum1+sum2)
# using array values are not been concadinated and values are not (,) seperated they are
# output is 20+10=30 30+20=50 40+30=70
# so I got the sum

[20 30 40] [10 20 30]
[30 50 70]


In [15]:
import numpy as np
# if array is not proper then it will give error like if one element is missing and in another array extra element is present 
ex=np.array([1,2,3])
ex2=np.array([1,2,5.9])
print(ex+ex2)


[2.  4.  8.9]


In [ ]:
# Question how to remove float value for other element's

In [19]:
# Multi-Dimentional array
mul_arr=np.array([[1,2,3,4,5],[6,7,8,9,10]]) #2D Array
# mul_arr=np.array([[1,2,3,4,5][6,7,8,9,10][11,12,13,14,15]]) #3D Array
print(mul_arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [32]:
# Slicing in Array's
mul_arr=np.array([1,2,3,4,5]) #2D Array
print(mul_arr[0:3]) # It has sliced the elements from 0 index till 3 index
print(mul_arr[2:]) # It has sliced the elements from 2 index till last index of an array


[1 2 3]
[3 4 5]


In [35]:
# Slicing in Multi-Array's
mul_arr=np.array([[1,2,3,4,5],[6,7,8,9,10]]) #2D Array
print(mul_arr[0:2,0:3]) 
# Output [[1 2][6 7]]
#  Have done slycing in multi-array


[[1 2 3]
 [6 7 8]]


In [42]:
# Slicing in Multi-Array's
# Q print 2,3 in first array
mul_arr=np.array([[1,2,3,4,5],[6,7,8,9,10]]) #2D Array
print(mul_arr[0,1:3]) 
# Output [2 3] 
# 0 is the index of 1 array total 3 arr technically 2 so 0 is refering to the index of the perticular array
#  Have done slycing in multi-array


[2 3]


In [3]:
# Attributes in Array
# np.shape
import numpy as np
mul_arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(np.shape(mul_arr))

# np.shape() give the number of rows and columns as 2 Rows and 5 column 

(2, 5)


In [4]:
# np.size
import numpy as np
mul_arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(np.size(mul_arr))
# np.size() give the total number of element present in the array's

10


In [6]:
# np.ndim to check dimentions 
# syntax => ndim()
import numpy as np
mul_arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(np.ndim(mul_arr))
# np.ndim() give the total dimension of the array's like 1D or 2D 

2


In [9]:
# np.dtype 
# syntax => dtype()
import numpy as np
mul_arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(mul_arr.dtype)
# mul_arr.dtype() give the type of the interger

int32


In [ ]:
# Inspecting an Array
# All about array is known as Inspecting in array
a.shape-Array Dimensions
len(a)-Length of array
a.ndim-Number of array dimensions
a.size-Number of array element
a.dtype-Data type of array elements
a.astype(int)-Convert on array to a diffrent type

In [9]:
import numpy as np
mul_arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(np.shape(mul_arr)) #rows, colums
print(len(mul_arr)) # length of array
print(np.ndim(mul_arr)) # dimention of array 1D 2D
print(np.size(mul_arr)) # number of elemnts
print(mul_arr.dtype) #type of data
print(mul_arr.astype(int)) #change the data type

(2, 5)
2
2
10
int32
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [16]:
# Mathematical Operation and Functions on Arrays
Addition: np.add()
Subtraction: np.subtract()
Multiplication: np.multiply()
Division: np.divide()
Exponentiation: np.exp()
Logarithm: np.log()
Square root: np.sqrt()
Trigonometric functions: np.sin(), np.cos(), np.tan(), etc.
Statistical functions: np.mean(), np.median(), np.std(), etc.

SyntaxError: invalid syntax (3039145771.py, line 8)

In [16]:
# Mathematical Operation and Functions on Arrays
Addition: np.add()
Subtraction: np.subtract()
Multiplication: np.multiply()
Division: np.divide()
Exponentiation: np.exp()
Logarithm: np.log()
Square root: np.sqrt()
Trigonometric functions: np.sin(), np.cos(), np.tan(), etc.
Statistical functions: np.mean(), np.median(), np.std(), etc.

SyntaxError: invalid syntax (3039145771.py, line 8)

In [16]:
# Mathematical Operation and Functions on Arrays
Addition: np.add()
Subtraction: np.subtract()
Multiplication: np.multiply()
Division: np.divide()
Exponentiation: np.exp()
Logarithm: np.log()
Square root: np.sqrt()
Trigonometric functions: np.sin(), np.cos(), np.tan(), etc.
Statistical functions: np.mean(), np.median(), np.std(), etc.

SyntaxError: invalid syntax (3039145771.py, line 8)

In [16]:
# Mathematical Operation and Functions on Arrays
Addition: np.add()
Subtraction: np.subtract()
Multiplication: np.multiply()
Division: np.divide()
Exponentiation: np.exp()
Logarithm: np.log()
Square root: np.sqrt()
Trigonometric functions: np.sin(), np.cos(), np.tan(), etc.
Statistical functions: np.mean(), np.median(), np.std(), etc.

SyntaxError: invalid syntax (3039145771.py, line 8)

In [17]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Addition
result_addition = np.add(arr1, arr2)

# Subtraction
result_subtraction = np.subtract(arr1, arr2)

# Multiplication
result_multiplication = np.multiply(arr1, arr2)

# Division
result_division = np.divide(arr1, arr2)

# Exponentiation
result_exp = np.exp(arr1)

# Logarithm 
result_log = np.log(arr1)

# Square root
arr = np.array([1, 4, 9])
result_sqrt = np.sqrt(arr)

# Trigonometry
result_sin = np.sin(arr1)
result_cos = np.cos(arr1)
result_tan = np.tan(arr1)

print("Addition:", result_addition)
print("Subtraction:", result_subtraction)
print("Multiplication:", result_multiplication)
print("Division:", result_division)
print("Exponentiation:", result_exp)
print("Logarithm:", result_log)


print("Square root:", result_sqrt)

print("Trigonometry Function")
print("Sine:", result_sin)
print("Cosine:", result_cos)
print("Tangent:", result_tan)



Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]
Exponentiation: [ 2.71828183  7.3890561  20.08553692]
Logarithm: [0.         0.69314718 1.09861229]
Square root: [1. 2. 3.]
Trigonometry Function
Sine: [0.84147098 0.90929743 0.14112001]
Cosine: [ 0.54030231 -0.41614684 -0.9899925 ]
Tangent: [ 1.55740772 -2.18503986 -0.14254654]


In [17]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Addition
result_addition = np.add(arr1, arr2)

# Subtraction
result_subtraction = np.subtract(arr1, arr2)

# Multiplication
result_multiplication = np.multiply(arr1, arr2)

# Division
result_division = np.divide(arr1, arr2)

# Exponentiation
result_exp = np.exp(arr1)

# Logarithm 
result_log = np.log(arr1)

# Square root
arr = np.array([1, 4, 9])
result_sqrt = np.sqrt(arr)

# Trigonometry
result_sin = np.sin(arr1)
result_cos = np.cos(arr1)
result_tan = np.tan(arr1)

print("Addition:", result_addition)
print("Subtraction:", result_subtraction)
print("Multiplication:", result_multiplication)
print("Division:", result_division)
print("Exponentiation:", result_exp)
print("Logarithm:", result_log)


print("Square root:", result_sqrt)

print("Trigonometry Function")
print("Sine:", result_sin)
print("Cosine:", result_cos)
print("Tangent:", result_tan)



Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]
Exponentiation: [ 2.71828183  7.3890561  20.08553692]
Logarithm: [0.         0.69314718 1.09861229]
Square root: [1. 2. 3.]
Trigonometry Function
Sine: [0.84147098 0.90929743 0.14112001]
Cosine: [ 0.54030231 -0.41614684 -0.9899925 ]
Tangent: [ 1.55740772 -2.18503986 -0.14254654]


In [17]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Addition
result_addition = np.add(arr1, arr2)

# Subtraction
result_subtraction = np.subtract(arr1, arr2)

# Multiplication
result_multiplication = np.multiply(arr1, arr2)

# Division
result_division = np.divide(arr1, arr2)

# Exponentiation
result_exp = np.exp(arr1)

# Logarithm 
result_log = np.log(arr1)

# Square root
arr = np.array([1, 4, 9])
result_sqrt = np.sqrt(arr)

# Trigonometry
result_sin = np.sin(arr1)
result_cos = np.cos(arr1)
result_tan = np.tan(arr1)

print("Addition:", result_addition)
print("Subtraction:", result_subtraction)
print("Multiplication:", result_multiplication)
print("Division:", result_division)
print("Exponentiation:", result_exp)
print("Logarithm:", result_log)


print("Square root:", result_sqrt)

print("Trigonometry Function")
print("Sine:", result_sin)
print("Cosine:", result_cos)
print("Tangent:", result_tan)



Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]
Exponentiation: [ 2.71828183  7.3890561  20.08553692]
Logarithm: [0.         0.69314718 1.09861229]
Square root: [1. 2. 3.]
Trigonometry Function
Sine: [0.84147098 0.90929743 0.14112001]
Cosine: [ 0.54030231 -0.41614684 -0.9899925 ]
Tangent: [ 1.55740772 -2.18503986 -0.14254654]


In [17]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Addition
result_addition = np.add(arr1, arr2)

# Subtraction
result_subtraction = np.subtract(arr1, arr2)

# Multiplication
result_multiplication = np.multiply(arr1, arr2)

# Division
result_division = np.divide(arr1, arr2)

# Exponentiation
result_exp = np.exp(arr1)

# Logarithm 
result_log = np.log(arr1)

# Square root
arr = np.array([1, 4, 9])
result_sqrt = np.sqrt(arr)

# Trigonometry
result_sin = np.sin(arr1)
result_cos = np.cos(arr1)
result_tan = np.tan(arr1)

print("Addition:", result_addition)
print("Subtraction:", result_subtraction)
print("Multiplication:", result_multiplication)
print("Division:", result_division)
print("Exponentiation:", result_exp)
print("Logarithm:", result_log)


print("Square root:", result_sqrt)

print("Trigonometry Function")
print("Sine:", result_sin)
print("Cosine:", result_cos)
print("Tangent:", result_tan)



Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]
Exponentiation: [ 2.71828183  7.3890561  20.08553692]
Logarithm: [0.         0.69314718 1.09861229]
Square root: [1. 2. 3.]
Trigonometry Function
Sine: [0.84147098 0.90929743 0.14112001]
Cosine: [ 0.54030231 -0.41614684 -0.9899925 ]
Tangent: [ 1.55740772 -2.18503986 -0.14254654]
