In [ ]:
# Numpy it is the python library which is used for calculating matamatical operation 
# Num py means Numerical in python shortly known as Numpy
# Array defined as collection of items that are stored at contiguous memory locations.
# it is a container which can hold a fixed number of items, and these should of same type
# Combination of arrays saves a time as it reduce the overall size of the code.

In [2]:
import numpy as np

l1=[20,30,40]
l2=[50,60,90]
print(l1+l2)
# here using list values are comma (,) sepereated and it has concadinated the list


[20, 30, 40, 50, 60, 90]


In [5]:
sum1=np.array([20,30,40])
sum2=np.array([10,20,30])
print(sum1,sum2)
print(sum1+sum2)
# using array values are not been concadinated and values are not (,) seperated they are
# output is 20+10=30 30+20=50 40+30=70
# so I got the sum

[20 30 40] [10 20 30]
[30 50 70]


In [15]:
import numpy as np
# if array is not proper then it will give error like if one element is missing and in another array extra element is present 
ex=np.array([1,2,3])
ex2=np.array([1,2,5.9])
print(ex+ex2)


[2.  4.  8.9]


In [ ]:
# Question how to remove float value for other element's

In [19]:
# Multi-Dimentional array
mul_arr=np.array([[1,2,3,4,5],[6,7,8,9,10]]) #2D Array
# mul_arr=np.array([[1,2,3,4,5][6,7,8,9,10][11,12,13,14,15]]) #3D Array
print(mul_arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [32]:
# Slicing in Array's
mul_arr=np.array([1,2,3,4,5]) #2D Array
print(mul_arr[0:3]) # It has sliced the elements from 0 index till 3 index
print(mul_arr[2:]) # It has sliced the elements from 2 index till last index of an array


[1 2 3]
[3 4 5]


In [35]:
# Slicing in Multi-Array's
mul_arr=np.array([[1,2,3,4,5],[6,7,8,9,10]]) #2D Array
print(mul_arr[0:2,0:3]) 
# Output [[1 2][6 7]]
#  Have done slycing in multi-array


[[1 2 3]
 [6 7 8]]


In [42]:
# Slicing in Multi-Array's
# Q print 2,3 in first array
mul_arr=np.array([[1,2,3,4,5],[6,7,8,9,10]]) #2D Array
print(mul_arr[0,1:3]) 
# Output [2 3] 
# 0 is the index of 1 array total 3 arr technically 2 so 0 is refering to the index of the perticular array
#  Have done slycing in multi-array


[2 3]
